{
 "title": "Electrical SQL",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<br>\r\n<a href=\"https://grafana.davidjarty.com/d/V_4SWBA7z/quicklook-sql\">Return Home</a> "
   }
  },
  {
   "title": "House Voltage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT\n  CONVERT_TZ(datetime, \"US/EASTERN\", \"UTC\") AS \"time\",\n  Voltage\nFROM status\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime"
    },
    {
     "rawSql": "SELECT\n  CONVERT_TZ(datetime, \"US/EASTERN\", \"UTC\") AS \"time\",\n  soc as \"State of Charge\"\nFROM status\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime"
    }
   ]
  },
  {
   "title": "House Load and Current",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "rawSql": "SELECT\n  CONVERT_TZ(datetime, \"US/EASTERN\", \"UTC\") AS \"time\",\n  netCurrent as \"Net Current\"\nFROM status\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime"
    },
    {
     "rawSql": "SELECT\n  CONVERT_TZ(datetime, \"US/EASTERN\", \"UTC\") AS \"time\",\n  amps * -1 as \"Load\"\nFROM status\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime"
    }
   ]
  },
  {
   "title": "House Battery Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT\n  CONVERT_TZ(datetime, \"US/EASTERN\", \"UTC\") AS \"time\",\n  housebatttemp AS \"Temperature\"\nFROM status\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime"
    },
    {
     "rawSql": "SELECT\n  CONVERT_TZ(datetime, \"US/EASTERN\", \"UTC\") AS \"time\",\n  minhousebatttemp AS \"Min Temp\"\nFROM status\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime"
    },
    {
     "rawSql": "SELECT\n  CONVERT_TZ(datetime, \"US/EASTERN\", \"UTC\") AS \"time\",\n  maxhousebatttemp AS \"Max Temp\"\nFROM status\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Engine Voltage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  CONVERT_TZ(datetime, \"US/EASTERN\", \"UTC\") AS \"time\",\n  engv as \"Voltage\"\nFROM status\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime"
    },
    {
     "rawSql": "SELECT\n  CONVERT_TZ(datetime, \"US/EASTERN\", \"UTC\") AS \"time\",\n  maxengv as \"Max Voltage\"\nFROM status\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime"
    },
    {
     "rawSql": "SELECT\n  CONVERT_TZ(datetime, \"US/EASTERN\", \"UTC\") AS \"time\",\n  minengv \"Min Voltage\"\nFROM status\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Thruster Voltage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  CONVERT_TZ(datetime, \"US/EASTERN\", \"UTC\") AS \"time\",\n  auxv as \"Voltage\"\nFROM status\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime"
    },
    {
     "rawSql": "SELECT\n  CONVERT_TZ(datetime, \"US/EASTERN\", \"UTC\") AS \"time\",\n  maxauxv as \"Max Voltage\"\nFROM status\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime"
    },
    {
     "rawSql": "SELECT\n  CONVERT_TZ(datetime, \"US/EASTERN\", \"UTC\") AS \"time\",\n  minauxv as \"Min Voltage\"\nFROM status\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime"
    }
   ]
  }
 ]
}