{
 "title": "Engine SQL",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "<br>\r\n<a href=\"https://home_based_server.com.com/d/V_4SWBA7z/quicklook-sql?orgId=1\">Return Home</a> "
   }
  },
  {
   "title": "Engine Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "rawSql": "SELECT\n  CONVERT_TZ(datetime, \"US/EASTERN\", \"UTC\") AS \"time\",\n  engTemp as \"Engine Temperature\", maxEngTemp as \"Max Engine Temp\", minEngTemp as \"Min Engine Temp\"\nFROM status\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Exhaust Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "rawSql": "SELECT\n  CONVERT_TZ(datetime, \"US/EASTERN\", \"UTC\") AS \"time\",\n  exhaustTemp as \"Exhaust Temperature\", maxExhaustTemp as \"Max Exhaust Temp\", minExhaustTemp as \"Min Exhaust Temp\"\nFROM status\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime"
    }
   ]
  },
  {
   "title": "RPM's",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "rawSql": "SELECT\n  CONVERT_TZ(datetime, \"US/EASTERN\", \"UTC\") AS \"time\",\n  rpms as \"RPMs\", minRPMs as \"Min RPMs\", maxRPMs as \"Max RPMS\"\nFROM status\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime"
    }
   ]
  }
 ]
}