{
 "title": "Environment SQL",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "<br>\r\n<a href=\"https://home_based_server.com.com/d/V_4SWBA7z/quicklook-sql?orgId=1&refresh=1m\">Return Home</a> "
   }
  },
  {
   "title": "Cabin Temp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "rawSql": "SELECT\n  CONVERT_TZ(datetime, \"US/EASTERN\", \"UTC\") AS \"time\",\n  temperature as \"Cabin temperature\"\nFROM status\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Heel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "rawSql": "SELECT\n  CONVERT_TZ(datetime, \"US/EASTERN\", \"UTC\") AS \"time\",\n  heel as \"Heel\", maxh as \"Max Heel\", minh as \"Min Heel\"\nFROM status\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Cabin VOC's",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\n  CONVERT_TZ(datetime, \"US/EASTERN\", \"UTC\") AS \"time\",\n  gasLevel as \"VOC Level\", maxGasLevel as \"Max VOC Level\", minGasLevel as \"Min VOC Level\"\nFROM status\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime"
    }
   ]
  }
 ]
}