{
 "title": "Quicklook SQL",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 0 },
   "options": {
    "content": "<br>\n<a href=\"https://home_based_server.com.com/d/MGOzIDmRz/quicklook\">Online Version</a>"
   }
  },
  {
   "title": "Last Reading",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  CONVERT_TZ(datetime, \"US/Eastern\", \"UTC\") AS \"time\",\n  netCurrent\nFROM status\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Battery Voltages",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  CONVERT_TZ(datetime, \"US/Eastern\", \"UTC\") AS \"time\",\n  voltage\nFROM status\nWHERE\n  $__timeFilter(datetime)\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  CONVERT_TZ(datetime, \"US/Eastern\", \"UTC\") AS \"time\",\n  engv\nFROM status\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime"
    },
    {
     "rawSql": "SELECT\n  CONVERT_TZ(datetime, \"US/Eastern\", \"UTC\") AS \"time\",\n  auxv\nFROM status\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime"
    }
   ]
  },
  {
   "title": "House Current",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  CONVERT_TZ(datetime, \"US/Eastern\", \"UTC\") AS \"time\",\n  netCurrent\nFROM status\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime"
    }
   ]
  },
  {
   "title": "House Loads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  CONVERT_TZ(datetime, \"US/Eastern\", \"UTC\") AS \"time\",\n  amps * -1 \nFROM status\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime"
    }
   ]
  },
  {
   "title": "House State of Charge",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  CONVERT_TZ(datetime, \"US/Eastern\", \"UTC\") AS \"time\",\n  soc\nFROM status\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime"
    }
   ]
  },
  {
   "title": "House Batt Temp",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  housebatttemp\nFROM status\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Tanks",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  CONVERT_TZ(datetime, \"US/Eastern\", \"UTC\") AS \"time\",\n  water2 as \"Front Water\"\nFROM status\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime"
    },
    {
     "rawSql": "SELECT\n  CONVERT_TZ(datetime, \"US/Eastern\", \"UTC\") AS \"time\",\n  water1 as \"Aft Water\"\nFROM status\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime"
    },
    {
     "rawSql": "SELECT\n  CONVERT_TZ(datetime, \"US/Eastern\", \"UTC\") AS \"time\",\n  fuel as \"Fuel\"\nFROM status\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime"
    }
   ]
  },
  {
   "title": "RPM's",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  CONVERT_TZ(datetime, \"US/Eastern\", \"UTC\") AS \"time\",\n  RPMs\nFROM status\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Engine Temperature",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  CONVERT_TZ(datetime, \"US/Eastern\", \"UTC\") AS \"time\",\n  engTemp\nFROM status\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Exhaust Temperature",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  CONVERT_TZ(datetime, \"US/Eastern\", \"UTC\") AS \"time\",\n  exhaustTemp\nFROM status\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Cabin Temperature",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  CONVERT_TZ(datetime, \"US/Eastern\", \"UTC\") AS \"time\",\n  temperature\nFROM status\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Heel",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 24 },
   "format": "none",
   "targets": [
    {
     "rawSql": "SELECT\n  CONVERT_TZ(datetime, \"US/Eastern\", \"UTC\") AS \"time\",\n  heel\nFROM status\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Cabin VOC's",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  CONVERT_TZ(datetime, \"US/Eastern\", \"UTC\") AS \"time\",\n  gasLevel\nFROM status\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Last Nav Time",
   "type": "table",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "targets": [
    {
     "rawSql": "SELECT\n  CONVERT_TZ(datetime, \"US/Eastern\", \"UTC\") AS \"time\",\n  unix_timestamp(lastNav) * 1000  \nFROM status\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime desc"
    }
   ]
  },
  {
   "title": "Last Bilge Time",
   "type": "table",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "rawSql": "SELECT\n  CONVERT_TZ(datetime, \"US/EASTERN\", \"UTC\") AS \"time\",\n  unix_timestamp(lastBilge) * 1000\nFROM status\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime desc"
    }
   ]
  },
  {
   "title": "Bilge Counter",
   "type": "table",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 28 },
   "targets": [
    {
     "rawSql": "SELECT\n  CONVERT_TZ(datetime, \"US/EASTERN\", \"UTC\") AS \"time\",\n  bilgecount\nFROM status\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime desc"
    }
   ]
  },
  {
   "title": "Location",
   "type": "pr0ps-trackmap-panel",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  latgps\nFROM status\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime"
    },
    {
     "rawSql": "SELECT\n  datetime AS \"time\",\n  longps\nFROM status\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime"
    }
   ]
  }
 ]
}