{
 "title": "Quicklook",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 0 },
   "options": {
    "content": "<br>\n<a href=\"https://home_based_server.com.com/d/V_4SWBA7z/quicklook-sql\">Offline Version</a>\n"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 0 },
   "options": {
    "content": "<br>\n<a href=\"https://home_based_server.com.com/d/9hOtzu27k/nmea-quicklook\">NMEA Dashboard</a>\n"
   }
  },
  {
   "title": "Last Reading",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "electrical.batteries.Engine.voltage",
     "query": "SELECT last(\"value\") FROM \"electrical.batteries.Engine.voltage\"\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Battery Voltages",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "House V",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "electrical.batteries.House.voltage",
     "query": "SELECT last(\"value\") FROM \"electrical.batteries.House.voltage\" WHERE $timeFilter GROUP BY * ORDER BY DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Engine V",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "electrical.batteries.Engine.voltage",
     "query": "SELECT last(\"value\") FROM \"electrical.batteries.Engine.voltage\" WHERE $timeFilter GROUP BY * ORDER BY DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Thruster V",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "electrical.batteries.Thruster.voltage",
     "query": "SELECT last(\"value\") FROM \"electrical.batteries.Thruster.voltage\" WHERE $timeFilter GROUP BY * ORDER BY DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "House Current",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "electrical.batteries.House.current",
     "query": "SELECT last(\"value\") FROM \"electrical.batteries.House.current\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "House Loads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "electrical.batteries.House.load",
     "query": "SELECT last(\"value\") * -1 FROM \"electrical.batteries.House.load\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "House State of Charge",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "electrical.batteries.House.capacity.stateOfCharge",
     "query": "SELECT last(\"value\") FROM \"electrical.batteries.House.capacity.stateOfCharge\" WHERE $timeFilter GROUP BY * ORDER BY DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "House Batt Temp",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "electrical.batteries.House.temperature",
     "query": "SELECT (last(\"value\") -273) * 9/5 + 32 FROM \"electrical.batteries.House.temperature\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Tanks",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Front Water",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tanks.freshWater.front.currentLevel",
     "query": "SELECT last(\"value\") FROM \"tanks.freshWater.front.currentLevel\" WHERE $timeFilter GROUP BY * ORDER BY DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Aft Water",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tanks.freshWater.aft.currentLevel",
     "query": "SELECT last(\"value\") FROM \"tanks.freshWater.aft.currentLevel\" WHERE $timeFilter GROUP BY * ORDER BY DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RPM's",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "propulsion.main.revolutions",
     "query": "SELECT last(\"value\") * 60 FROM \"propulsion.main.revolutions\" WHERE $timeFilter GROUP BY * ORDER BY DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Engine Temperature",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (((last(\"value\") - 273) * 1.8) +32) FROM \"propulsion.main.coolantTemperature\" WHERE $timeFilter GROUP BY * ORDER BY DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Exhaust Temperature",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (((last(\"value\") - 273) * 1.8) +32) FROM \"propulsion.main.exhaustTemperature\" WHERE $timeFilter GROUP BY * ORDER BY DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cabin Temperature",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (((last(\"value\") - 273) * 1.8) +32) FROM \"environment.inside.mainCabin.temperature\" WHERE $timeFilter GROUP BY * ORDER BY DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heel",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 24 },
   "format": "none",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "navigation.attitude.heel",
     "query": "SELECT last(\"value\") FROM \"navigation.attitude.heel\" WHERE $timeFilter GROUP BY * ORDER BY DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cabin VOC's",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "environment.inside.mainCabin.voc",
     "query": "SELECT last(\"value\") FROM \"environment.inside.mainCabin.voc\" WHERE $timeFilter GROUP BY * ORDER BY DESC LIMIT 1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last Nav Time",
   "type": "table",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select last(stringValue) from \"navigation.datetime\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bilge Counter",
   "type": "table",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 28 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select last(stringValue) from \"sensors.bilge.time\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Bilge Counter",
   "type": "table",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 28 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select last(value) from \"sensors.bilge.count\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wifi SSID",
   "type": "table",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 30 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "environment.ssid",
     "query": "select last(stringValue) from \"environment.ssid\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Location",
   "type": "pr0ps-trackmap-panel",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "naviagion.position",
     "query": "SELECT last(\"lat\"), last(\"lon\") FROM \"navigation.position\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}