{
 "title": "Tanks SQL",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "<br>\r\n<a href=\"https://grafana.davidjarty.com/d/V_4SWBA7z/quicklook-sql\">Return Home</a> "
   }
  },
  {
   "title": "Front Water Level",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  CONVERT_TZ(datetime, \"US/EASTERN\", \"UTC\") AS \"time\",\n  water2\nFROM status\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Aft Water Level",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  CONVERT_TZ(datetime, \"US/EASTERN\", \"UTC\") AS \"time\",\n  water1\nFROM status\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime"
    }
   ]
  },
  {
   "title": "Fuel Level",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  CONVERT_TZ(datetime, \"US/EASTERN\", \"UTC\") AS \"time\",\n  fuel\nFROM status\nWHERE\n  $__timeFilter(datetime)\nORDER BY datetime"
    }
   ]
  }
 ]
}